#!/usr/bin/env python3
# =============================================================================
# BITMAP FONT GENERATOR
# =============================================================================
# Renders a TrueType font at one pixel size into a 1-bit C header consumed by
# main/ui/font.cpp; the struct layout here must match main/ui/font.h.
#
# Usage: gen_font.py <font.ttf> <pixel-size> <c-identifier> <out.h>
# Example: gen_font.py tools/fonts/AtkinsonHyperlegible-Regular.ttf 30 \
#              font_body main/ui/fonts/font_body.h

import sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0x7E
# Pixels darker than this become black; e-ink has no gray to spend on
# anti-aliasing, so a lowish threshold keeps thin strokes intact.
THRESHOLD = 120


# THE GLYPH RASTERIZER
# Renders one character and returns (bitmap_bytes, width, advance, x_offset).
def rasterize(font, ch, height, ascent):
    left, top, right, bottom = font.getbbox(ch)
    width = max(1, right - left)
    advance = max(1, round(font.getlength(ch)))
    img = Image.new("L", (width, height), 0)
    ImageDraw.Draw(img).text((-left, 0), ch, font=font, fill=255)
    row_bytes = (width + 7) // 8
    out = bytearray(row_bytes * height)
    px = img.load()
    for y in range(height):
        for x in range(width):
            if px[x, y] >= THRESHOLD:
                out[y * row_bytes + x // 8] |= 0x80 >> (x % 8)
    return bytes(out), width, advance, left


# THE HEADER WRITER
# Emits the glyph table and packed bitmap as C arrays.
def main(argv):
    if len(argv) != 5:
        sys.exit(__doc__ or "usage: gen_font.py <ttf> <size> <name> <out.h>")
    ttf, size, name, out_path = argv[1], int(argv[2]), argv[3], argv[4]
    font = ImageFont.truetype(ttf, size)
    ascent, descent = font.getmetrics()
    height = ascent + descent

    glyphs, bitmap = [], bytearray()
    for code in range(FIRST, LAST + 1):
        data, width, advance, x_offset = rasterize(font, chr(code), height, ascent)
        glyphs.append((len(bitmap), width, advance, x_offset))
        bitmap += data

    with open(out_path, "w", newline="\n") as f:
        f.write("// =============================================================================\n")
        f.write(f"// {name.upper()} BITMAP FONT\n")
        f.write("// =============================================================================\n")
        f.write(f"// Generated by tools/gen_font.py from {ttf.split('/')[-1]} at {size} px.\n")
        f.write("// Do not edit; rerun the generator instead.\n")
        f.write("#pragma once\n\n#include \"ui/font.h\"\n\n")
        f.write(f"static const uint8_t {name}_bitmap[] = {{\n")
        for i in range(0, len(bitmap), 16):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",\n")
        f.write("};\n\n")
        f.write(f"static const FontGlyph {name}_glyphs[] = {{\n")
        for (offset, width, advance, x_offset), code in zip(glyphs, range(FIRST, LAST + 1)):
            f.write(f"    {{{offset}, {width}, {advance}, {x_offset}}},  // '{chr(code)}'\n")
        f.write("};\n\n")
        f.write(f"static const Font {name} = {{\n")
        f.write(f"    {height}, {ascent}, {round(height * 1.15)}, {FIRST}, {LAST},\n")
        f.write(f"    {name}_glyphs, {name}_bitmap,\n}};\n")
    print(f"{out_path}: {LAST - FIRST + 1} glyphs, height {height}, {len(bitmap)} bytes")


if __name__ == "__main__":
    main(sys.argv)
